"""empty message

Revision ID: 1a36ada339d1
Revises: 4dde61b9bef1
Create Date: 2020-01-16 13:45:51.770447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a36ada339d1"
down_revision = "4dde61b9bef1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_group", sa.Column("domain_id", sa.Integer(), nullable=False))
    op.drop_constraint("user_group_project_id_fkey", "user_group", type_="foreignkey")
    op.create_foreign_key(None, "user_group", "domain", ["domain_id"], ["id"])
    op.drop_column("user_group", "project_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_group",
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_group", type_="foreignkey")
    op.create_foreign_key(
        "user_group_project_id_fkey", "user_group", "project", ["project_id"], ["id"]
    )
    op.drop_column("user_group", "domain_id")
    # ### end Alembic commands ###
