"""empty message

Revision ID: 272bb4c5edfd
Revises: b0b8aaebbed9
Create Date: 2020-01-18 03:55:16.266535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "272bb4c5edfd"
down_revision = "b0b8aaebbed9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "is_active")
    # ### end Alembic commands ###
