"""empty message

Revision ID: 4dde61b9bef1
Revises: b7e7b6d4f900
Create Date: 2020-01-15 13:36:52.813399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dde61b9bef1'
down_revision = 'b7e7b6d4f900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_name_and_type_on_permission_table', 'permission', ['name', 'type'])
    op.drop_constraint('permission_name_type_key', 'permission', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('permission_name_type_key', 'permission', ['name', 'type'])
    op.drop_constraint('unique_name_and_type_on_permission_table', 'permission', type_='unique')
    # ### end Alembic commands ###
