"""empty message

Revision ID: 59ed53ed7f8f
Revises: aa05eb95ee90
Create Date: 2020-01-17 17:16:39.228403

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "59ed53ed7f8f"
down_revision = "aa05eb95ee90"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_permission", ["user_id", "permission_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_permission", type_="unique")
    # ### end Alembic commands ###
