"""empty message

Revision ID: b0b8aaebbed9
Revises: e760e415f09b
Create Date: 2020-01-18 00:09:33.614270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b8aaebbed9'
down_revision = 'e760e415f09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint(None, 'user_group_member', ['user_id'])
    op.create_unique_constraint(None, 'user_group_permission', ['group_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group_permission', type_='unique')
    op.drop_constraint(None, 'user_group_member', type_='unique')
    op.drop_column('permission', 'is_active')
    # ### end Alembic commands ###
