"""empty message

Revision ID: b7e7b6d4f900
Revises: 377b9a887471
Create Date: 2020-01-15 13:35:47.286541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e7b6d4f900'
down_revision = '377b9a887471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_constraint('permission_name_key', 'permission', type_='unique')
    op.create_unique_constraint(None, 'permission', ['name', 'type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permission', type_='unique')
    op.create_unique_constraint('permission_name_key', 'permission', ['name'])
    op.drop_column('domain', 'is_active')
    # ### end Alembic commands ###
