"""empty message

Revision ID: e760e415f09b
Revises: 59ed53ed7f8f
Create Date: 2020-01-17 23:05:43.080250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e760e415f09b'
down_revision = '59ed53ed7f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'is_active')
    # ### end Alembic commands ###
